

0-graph_create:
	gcc -Wall -Wextra -Werror -pedantic tests/0-main.c 0-graph_create.c -o 0-graph_create

1-graph_add_vertex:
	gcc -Wall -Wextra -Werror -pedantic -g3 tests/1-main.c 0-graph_create.c 1-graph_add_vertex.c graph_display.c

2-graph_add_edge:
	gcc -Wall -Wextra -Werror -pedantic -g3 tests/2-main.c 0-graph_create.c 1-graph_add_vertex.c 2-graph_add_edge.c graph_display.c

3-graph_delete:
	gcc -Wall -Wextra -Werror -pedantic -g3 tests/3-main.c 0-graph_create.c 1-graph_add_vertex.c 2-graph_add_edge.c 3-graph_delete.c graph_display.c

4-dfs:
	gcc -Wall -Wextra -Werror -pedantic -g3 tests/4-main.c 0-graph_create.c 1-graph_add_vertex.c 2-graph_add_edge.c 3-graph_delete.c 4-depth_first_traverse.c graph_display.c

5-bfs:
	gcc -Wall -Wextra -Werror -pedantic -g3 tests/5-main.c 0-graph_create.c 1-graph_add_vertex.c 2-graph_add_edge.c 3-graph_delete.c 5-breadth_first_traverse.c graph_display.c
